services:
  eos_connect:
    image: ghcr.io/wolfimbusch/eos_connect:nightly
    ports:
      - "8081:8081"
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped