"""Build the standalone flow diagram from the inline copy in the docs.

The "how it works" diagram exists twice, for one reason: the docs page embeds it
inline so its strokes and text inherit the page colour through ``currentColor``
and follow the theme, while ``README.md`` embeds it as an ``<img>``, which
inherits nothing and therefore needs the palette baked in.

Rather than maintain both, this generates the standalone file from the inline
one — edit ``docs/what-is/index.html`` and re-run::

    python scripts/build_flow_diagram.py

``tests/docs/test_docs_integrity.py::test_flow_diagram_copies_agree`` fails when
the two drift, which is what catches a forgotten re-run.
"""

import pathlib
import re
import sys
import xml.etree.ElementTree as ET

REPO = pathlib.Path(__file__).resolve().parents[1]
SOURCE = REPO / "docs/what-is/index.html"
TARGET = REPO / "docs/assets/images/eos_connect_flow.svg"

# Room around the drawing so nothing touches the card's rounded edge.
PAD = 14
# The docs' body stack. An <img> gets no page CSS, so the file has to name it.
FONT = "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif"
# What currentColor resolves to on the docs page (--text).
INK = "#d3d3d3"
CARD = "#3a3a3a"


def extract_inline_svg(html):
    match = re.search(r'<svg class="diagram".*?</svg>', html, re.S)
    if not match:
        raise SystemExit(f"no inline diagram found in {SOURCE}")
    return match.group(0)


def shift_down(markup, offset):
    """Move every drawn element down, leaving marker-internal geometry alone."""
    markup = re.sub(
        r'\b(y|y1|y2|cy)="(-?[\d.]+)"',
        lambda m: '%s="%g"' % (m.group(1), float(m.group(2)) + offset),
        markup,
    )
    # The single feedback path, whose verticals need the same offset.
    markup = re.sub(
        r'\bd="M (\d+) (\d+) V (\d+) H (\d+) V (\d+) H (\d+)"',
        lambda m: 'd="M %s %g V %g H %s V %g H %s"'
        % (
            m.group(1),
            int(m.group(2)) + offset,
            int(m.group(3)) + offset,
            m.group(4),
            int(m.group(5)) + offset,
            m.group(6),
        ),
        markup,
    )
    # The arrowhead lives in its own viewBox and must not move with the drawing.
    return markup.replace('refY="%g"' % (5 + offset), 'refY="5"')


def build():
    html = SOURCE.read_text(encoding="utf-8")
    svg = extract_inline_svg(html)

    aria = re.search(r'aria-label="([^"]*)"', svg, re.S).group(1)
    height = int(re.search(r'viewBox="0 0 620 (\d+)"', svg).group(1))

    body = svg.split(">", 1)[1].rsplit("</svg>", 1)[0]
    body = shift_down(body, PAD)
    body = body.replace("currentColor", INK)

    # Re-indent to this file's structure rather than the HTML's nesting depth.
    lines = [ln[28:] if ln.startswith(" " * 28) else ln.strip() for ln in body.splitlines()]
    body = "\n".join("        " + ln if ln.strip() else "" for ln in lines).strip("\n")

    total = height + PAD * 2
    out = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 620 {total}" width="620" height="{total}"
    role="img" aria-label="{aria}">
    <title>How EOS Connect works</title>
    <desc>The optimizer sits inside EOS Connect; an external server is an optional replacement.</desc>

    <!-- GENERATED by scripts/build_flow_diagram.py from the inline diagram in
         docs/what-is/index.html. Do not hand-edit: change the inline copy and
         re-run the script. This copy exists because README.md embeds it as an
         <img>, which cannot inherit currentColor. -->

    <rect width="620" height="{total}" rx="12" fill="{CARD}" />

    <g font-family="{FONT}">
{body}
    </g>
</svg>
"""
    ET.fromstring(out)  # fail loudly rather than shipping malformed markup
    return out


def main():
    svg = build()
    TARGET.write_text(svg, encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(REPO)} ({len(svg)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
