name: Nightly Build and Push

on:
  schedule: # runs on the default branch: master
  - cron: "0 2 * * *" # run at 2 AM UTC
  workflow_dispatch: # allows manual triggering of the workflow
  
jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/eos_connect_test:nightly .
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/eos_connect_test:nightly

